server:
  port: 0
spring:
  application:
    name: processing
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
management:
  endpoints:
    web:
      exposure:
        include: health
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/